import Head from "next/head";
import { Lexend_Deca } from "next/font/google";
import MyAppBar from "@/components/common/AppBar";
import NowPlaying from "@/components/homepage/NowPlaying";

import CommonStyles from "@/styles/common.module.css";
import { Container } from "@mui/material";
import Discover from "@/components/homepage/Discover";

const lexend_Deca = Lexend_Deca({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>CineCritic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${lexend_Deca.className}`}>
        <MyAppBar />
        <div className={CommonStyles.mainDiv}>
          <NowPlaying />
          <Discover />
        </div>
      </main>
    </>
  );
}
